### PR TITLE
add Position to RulesetRule

### LINKED ISSUE #1938: RulesetRule missing position arguments
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.x, v2.x

### Expected output

The ability to update a RulesetRule position by PATCH:

https://developers.cloudflare.com/ruleset-engine/rulesets-api/update-rule/#change-the-order-of-a-rule-in-a-ruleset

Looks to be missing from API docs too.

### Code demonstrating the issue

RulesetRule struct is missing Position field. https://github.com/cloudflare/cloudflare-go/blob/1096abb50b128c8c55e952a8d7cd1f894181da61/rulesets.go#L648-L663

### PR DESCRIPTION
**Pull request by vroy**
This will allow to update position of a specific rule in PATCH:

* fixes: https://github.com/cloudflare/cloudflare-go/issues/1938
* https://developers.cloudflare.com/ruleset-engine/rulesets-api/update-rule/#change-the-order-of-a-rule-in-a-ruleset

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
thanks for the PR however, the API schema documentation for `position` is missing so we cannot add it until that is resolved by the service team.

once that is added, it will automatically appear in 2.x.

**Comment by jacobbednarz** [comment]
apologies - i was looking at the wrong branch. this does already exist in the API schemas and the 2.x SDK. see https://github.com/cloudflare/cloudflare-go/blob/v2/rulesets/rule.go#L5341

as it exists in 2.x and isn't used elsewhere in the v0 library, i think we're fine to close this one out and recommend using 2.x instead of backporting this one.

**Comment by vroy** [comment]
Thanks, somehow missed when searching the v2 branch.

We'll certainly be looking at adopting 2.x SDK but until it becomes the main branch we're hesitant. Can this really not be backported?

Screenshot 2024-05-06 at 9 47 39 AM

**Comment by jacobbednarz** [comment]
as that release note mentions, it's stable for majority of projects. we are leaving that warning in place for now as we are still cleaning up type names, etc. which are technically breaking changes and folks should be aware of it.

we have no timeline on when we switch the primary branch (nor should it matter given that is a GitHub-ism; you can use any release with confidence that it will largely work). 

we have other tooling that is in the process of porting over to the new SDKs and until those are complete, the legacy SDK will remain as is today but we are not extending the current footprint _except_ where those tools depend on the legacy SDK (see examples of recent zero trust changes for Terraform). `rule.position` values are not used in downstream tooling today, so we don't have plans to backport and support it.

if you really want this but also want to stick onto v0, you can run these libraries side by side. check out cloudflare/terraform-provider-cloudflare#3262 if you'd like some prior art to use.

**Pull request closed without merging**
