### PR TITLE
fix(json): fix invalid field name json mapping for workers subdomain

### PR DESCRIPTION
**Pull request by infosec-au**
## Description

We were unable to use the function inside this Golang API to retrieve the accounts worker subdomain. This was because the API response is different to what the code is expecting. The JSON field name from the API response is `subdomain` where as this code was expecting `name`. Changing the expected field name allows for us to successfully obtain the cloudflare subdomain name via this golang api.

## Has your change been tested?

Yes it has been tested.

API response:

```
{
  "result": {
    "subdomain": "fifty-lashes-blah"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

With my code change:

```
workers subdomain {Name:fifty-lashes-blah}
```

Before my code change:

```
workers subdomain {Name:}
```

Code:

```
	api, err := cloudflare.NewWithAPIToken(token.ApiToken)
	if err != nil {
		return nil, errors.Wrap(err, "Failed to create cloudflare API session")
	}

	accs, _, err := api.Accounts(ctx, cloudflare.AccountsListParams{})
	if err != nil {
		return nil, errors.Wrap(err, "Failed to get cloudflare accounts")
	}

	var accountIds []string

	for _, acc := range accs {
		accountIds = append(accountIds, acc.ID)
	}

	for _, accIdentifier := range accountIds {
		workersSubdomain, err := api.WorkersGetSubdomain(ctx, cloudflare.AccountIdentifier(accIdentifier))
		if err != nil {
			return nil, errors.Wrap(err, "Failed to list cloudflare worker domains")
		}
		fmt.Printf("workers subdomain %+v", workersSubdomain)
	}
```

## Types of changes

What sort of change does your code introduce/modify?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
`name` is the publicly defined value in the API documentation so we'll need the team to update this accordingly.

see https://developers.cloudflare.com/api/operations/worker-subdomain-get-subdomain

**Comment by infosec-au** [comment]
Hi @jacobbednarz -

Will the API response change so that it is `name` in the response as the API docs suggest? or will the docs change so that they reference `subdomain` instead?

Thank you for responding

**Comment by jacobbednarz** [comment]
that's up to the team but this is technically a breaking change if the key is `subdomain` and not `name`.

**Comment by jacobbednarz** [comment]
@infosec-au this has been updated in the API documentation. if you add a changelog entry to this PR, we can get it merged.

**Comment by infosec-au** [comment]
Hi @jacobbednarz -

Can you please do this and get this merged, if you need it merged soon? I fixed this bug almost a year ago, and I don't have time right now to add a change log entry.

**Comment by jacobbednarz** [comment]
afraid not. you've made changes to your fork's `master` which has branch protection enabled and is not editable by maintainers of the source repository. 

if you don't have time to add the file, that's fine we can close it out and some near future work can address it.

**Comment by jacobbednarz** [comment]
closing PR due to age and lack of activity. if someone wants to revive, please do otherwise this will be covered in v2 automatically.

**Pull request closed without merging**
