### PR TITLE
DLP-631 Add support for DLP Endpoints

### PR DESCRIPTION
**Pull request by GreenStage**
Adds support for Zero Trust DLP endpoints

## Description

We are adding DLP endpoints support to cloudflare-go and terraform, as we prepare to go live in production.

## Has your change been tested?

Manually, through a simple program running DLP endpoint calls against my account.

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ X ] My code follows the code style of this project.
- [ X ] My change requires a change to the documentation.
- [ X  ] I have updated the documentation accordingly.
- [ X ] I have added tests to cover my changes.
- [ X ] All new and existing tests passed.
- [ X ] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.  --> **PENDING RELEASE**

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
i went ahead and updated the methods to match the [`experimental`](https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.md) approach for method signatures and conventions to keep it in line with where we are heading for these methods. hopefully, the simplification of these methods to be around the generic `DLPProfile` with the option to target custom or predefined types demonstrates the benefits of this type of approach.

i've also swapped `Enabled` to be a boolean pointer. we've had too many issues with Terraform to use a straight boolean so this allows us some flexibility when we get to that integration.

**Comment by GreenStage** [comment]
Hi @jacobbednarz , thanks for helping out!
One small concern:
You can only create and delete **custom** profiles. So changing the signature of the CreateDLPCustomProfile/DeleteDLPCustomProfile to CreateDLPProfile/DeleteDLPProfile may promote confusion.

**Comment by jacobbednarz** [comment]
it's definitely a concern but something we can rely on the API/docs to help guide (also, the `Delete` is custom only for now via the URL). do we currently have API responses in place to help with this?

the thing I'm aiming to avoid here is down the track if we allow predefined profiles modifiable/deletable and we have to change the method signatures again. it's a pattern that keeps popping up where we have initial constraints but eventually loosen them off and cause SDK users an annoying migration.

**Comment by GreenStage** [comment]
Totally understand you.

As you said, both the create endpoint to delete endpoint urls are specifically under the /custom path.  The API does not have routes for DELETE /predefined/{id} or POST /predefined. This will result in 404s.

I agree with your concern for flexibility and future retro-compatibility, but we need to figure out a way to avoid confusion here

**Comment by GreenStage** [comment]
the way i see it, we have 2 options:
1) add a if check on the create/delete function for "custom" type;
2) change the signatures to CreateDLPCustomProfile and DeleteDLPCustomProfile

**Comment by jacobbednarz** [comment]
let's go with #1. we can have it throw an exception for requests that are not custom and keep that logic internal to the method. 

I'll push up a PR for this later today.

**Comment by jacobbednarz** [comment]
have made this update for the `Create` in #1113. the `Delete` is already using `custom` in the path so would already only apply to those profiles.

**Pull request merged**
