### PR TITLE
Run gofmt

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Ah, scratch that. The `IsAlias` method isn't working on 1.8 as it [was introduced in 1.9](https://golang.org/pkg/go/types/#TypeName.IsAlias).

@patryk What is the language version support policy where? Do we need to support 1.8 anymore?

**Comment by gliptak** [comment]
```golint HEAD``` is broken for ```Go``` ```1.7``` and ```1.8``` https://travis-ci.org/golang/lint/builds/444499244

**Comment by jacobbednarz** [comment]
@gliptak `golint HEAD` [looks good again](https://travis-ci.org/golang/lint/builds/440240105). Do you mind rebasing this and force pushing to trigger a build?

**Comment by gliptak** [comment]
@jacobbednarz ```golint``` ```1.8``` is stiil broken (https://travis-ci.org/golang/lint/builds/440240105 ran 11 days ago ...)

**Comment by jacobbednarz** [comment]
🤦‍♂️ apologies - That's what I get for having a billion tabs open and skipping through it.

**Comment by gliptak** [comment]
@jacobbednarz no worries. thank you for reviewing

**Comment by patryk** [comment]
I have dropped Go 1.8 as test target. We don't need to worry about unmaintained branches.

**Comment by patryk** [comment]
I'm actually considering dropping 1.9.x as well and just stick to Google's policy of supporting two last major versions.

**Pull request merged**
