### PR TITLE
Update pagination to compute current page based off total_count

### PR DESCRIPTION
**Pull request by jroyal**
Also fixes pagination for a few Access Resources

## Description

In terraform, if you try to use the [Access Application Resource](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application.html) in a datasource it will fail to find the app because the List function will only check the first page. 

## Has your change been tested?

Unit tests and a local reproduction of the original issue that is now resolved.

## Types of changes

What sort of change does your code introduce/modify?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jroyal** [comment]
@jacobbednarz tbh I'm a little hesitant on the new commit about changing `total_count` in all the tests. That was why the tests were failing.

I think its the correct fix, since `count` should always equal `total_count` if there are less than 1 page worth of results. Since most tests only have 1 item this should make the tests match real behavior. I couldn't decide if should try to handle that differently though in pagination.go?

**Comment by jacobbednarz** [comment]
iirc, the test data came from the old API docs which didn't have real validation so it may have been incorrect the entire time. I think fixing the tests here is the right move if we've uncovered issues.

**Comment by jacobbednarz** [comment]
it's worth noting, we also don't have thorough impossible logic checks for pagination which we _could_ firm that up but I suspect there are some services that have a misunderstanding of all the result info fields so it may be better to fix to be more clear instead. 

(the second part is already something we are speaking about internally too)

**Comment by jacobbednarz** [comment]
thanks for this!

**Pull request merged**
