### PR TITLE
Allow for autopagination with custom page size

### PR DESCRIPTION
**Pull request by arturhoo**
Signed-off-by: Artur Rodrigues <artur.rodrigues@lacework.net>

On https://github.com/cloudflare/cloudflare-go/pull/1151, `ListDNSRecordsParams` was introduced, which allows for users of the library to "search" for a specific page. What is not possible, however, is to have auto-pagination (i.e.: fetch all results) with a customer page size.

This level of flexibility is interesting for those seeking to reduce the number of API calls made to Cloudflare if they're facing rate limits.

## Description

On https://github.com/cloudflare/cloudflare-go/pull/1151, `ListDNSRecordsParams` was introduced, which embeds the [`ResultInfo`](https://github.com/cloudflare/cloudflare-go/blob/63d7aa85c4216e423033ce2f3315a672b657afd6/cloudflare.go#L473-L482) struct.

This bring the library to the same level of flexibility as the [API itself](https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records). However, users opting for the auto-pagination feature are restricted to the default `PerPage` [value of 50](https://github.com/cloudflare/cloudflare-go/blob/master/dns.go#L173).

If users decide to pass in a custom `PerPage` value, auto-pagination is silently turned off, with just the first page being returned.

This PR simply changes the logic in ListDNSRecords to turn off `autopaginate` only if `Page` is passed in. With the current auto-pagination logic, a larger `PerPage` can be used with no side-effects. This seems sensible, as auto-pagination is an added feature of the library on top of the API.

Imho, adding some documentation to the behaviour (current and new) is probably a good idea.

## Has your change been tested?

Added new unit test for the pagination behaviour with a custom `PerPage` value.
I've also validated it manually using `flarectl`.

## Screenshots (if appropriate):

N/A

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Review by jacobbednarz — CHANGES_REQUESTED** [review]
thanks for the PR but we won't be accepting it as is. the library has the convention that if you provide any pagination options, we don't paginate. this gives us the best of both worlds where those who don't care for internal pagination can easily get all values but if someone needs to control pagination, they have full control over it. we won't be changing this in the foreseeable future. 

if the per page count is problematic, we evaluate that on an endpoint by endpoint basis. generally, that is 50 records however, for DNS we can have a higher threshold given the service defaults to a much higher value (such as 1000).

**Comment by arturhoo** [comment]
Thanks for the thoughtful response.

In this case, perhaps the default should be changed from 50 in the library to 100, matching the default value of the API itself? https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records

> the library has the convention that if you provide any pagination options, we don't paginate. this gives us the best of both worlds where those who don't care for internal pagination can easily get all values but if someone needs to control pagination, they have full control over it.

The consistency bit makes a lot of sense! However, I think the best of both worlds is still achieved: those wanting the flexibility of controlling pagination themselves only have to set `Page`, while those who don't can continue to call the method without passing the attributes from `ResultInfo`. Perhaps an explicit auto-pagination attribute in the `ResultInfo` struct would make it better? Let me know if you'd be open to that. Thanks,

**Comment by jacobbednarz** [comment]
> In this case, perhaps the default should be changed from 50 in the library to 100, matching the default value of the API itself? https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records

apologies if it wasn't clear; this is what i suggesting above but only for the DNS records endpoint. others we will keep at 50 since that it a sensible default for the majority of resources.

> I think the best of both worlds is still achieved: those wanting the flexibility of controlling pagination themselves only have to set `Page`, while those who don't can continue to call the method without passing the attributes from `ResultInfo`

this assumption doesn't match the feedback we've received. Go SDK users want the ability to control both aspects of the pagination which is why the or conditional disables automatic pagination if either are provided.

> Perhaps an explicit auto-pagination attribute in the ResultInfo struct would make it better? Let me know if you'd be open to that.

maybe at a later date, but not right now. we'll be looking to transition to Go generics in the future for a pagination helper which will trim down the boilerplate we reuse however, we have no solid plans to replace the convention for now.

**Comment by arturhoo** [comment]
> apologies if it wasn't clear; this is what i suggesting above but only for the DNS records endpoint. others we will keep at 50 since that it a sensible default for the majority of resources.

I'll open a new PR with only this change!

**Pull request closed without merging**
