### PR TITLE
get and edit WAF rule groups

### LINKED ISSUE #321: additional WAF rule endpoint support
support should be added for some missing WAF endpoints...

https://api.cloudflare.com/#waf-rule-packages-firewall-package-details
https://api.cloudflare.com/#waf-rule-packages-edit-firewall-package
https://api.cloudflare.com/#waf-rule-groups-list-rule-groups
https://api.cloudflare.com/#waf-rule-groups-rule-group-details
https://api.cloudflare.com/#waf-rule-groups-edit-rule-group

## Context

I'm prepared to work on terraform additions to add additional WAF data sources, as well and resources to support reading and configuring of WAF rule packages and groups.

These additional endpoints will be needed to implement these.

### PR DESCRIPTION
**Pull request by sbfaulkner**
This PR adds entry-points to get and edit WAF rule groups as per https://api.cloudflare.com/#waf-rule-groups-rule-group-details and https://api.cloudflare.com/#waf-rule-groups-edit-rule-group 

This adds the missing pieces and closes #321

/cc @patryk @jacobbednarz 

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sbfaulkner** [comment]
@patryk when this one gets merged it will probably be useful to have a release cut so that we can use it as a dependency for some additions to the terraform provider

**Comment by sbfaulkner** [comment]
🛎 @patryk

**Comment by sbfaulkner** [comment]
any way we can get this merged and a release cut?

**Comment by patryk** [comment]
My apologies for the delay. Didn't notice you pinged me here. I'll cut a release shortly.

**Pull request merged**
