### PR TITLE
[feat] ListZones internal pagination

### PR DESCRIPTION
**Pull request by Oldsouldier**
Collect all available zones sequentially and return them to the user,
rather than just the first page.  The maximum page size is used
to minimize API calls.

This matches the DNSRecords implementation, and allows simple
access to all zones until general pagination can be implemented.

### CODE REVIEW

**Comment by Oldsouldier** [comment]
Related issues: #6, #4 , and #135

**Comment by Oldsouldier** [comment]
@elithrar Any thoughts on this? Seems like the issue has been open a while. If progress has been made on a general pagination technique i can align to that instead.

**Comment by elithrar** [comment]
Hey @Oldsouldier - I'm no longer at Cloudflare, so may not be able to help with this directly. @tomlikestorock may be able to take a look at this.

**Comment by njuettner** [comment]
It would be nice to merge it :).

We use your library in one of our projects, see:
https://github.com/kubernetes-incubator/external-dns/blob/master/provider/cloudflare.go

Recently we were asked why it only returns the first page to list zones. Unfortunately the only option would be to use the API directly.

**Comment by terinjokes** [comment]
I'd prefer not baking automatic pagination into individual API endpoints, but instead allow users to pass in the paging information. Then other functions could be written to wrap an automatic paginate.

Over in the JS bindings, I'd been thinking over using function options on the endpoint functions, to allow these to be pretty flexible. Below would be an example of this idea in Go.

```go
// ListZonesContext lists zones on an account with context and option support
func (api *API) ListZonesContext(ctx context.Context, z string, opt... Option) (ZonesResponse, error) {
  // Return a response type that includes the API meta information, that includes
  // the pagination information.
}

// WithZonesFilter takes a list of zone names
// to filter against.
func WithZonesFilter(z... string) Option {
  return func(opt requestOpt) {
    opt.zones = z
  }
}

// WithPagination allows the consumer to specify the pagination options
// for the request.
func WithPagination(page, count int) Option {
  return func(opt requestOpt) {
    opt.perPage = 25
    opt.page = 3
  }
}
```

**Comment by Oldsouldier** [comment]
@terinjokes ,  I completely agree with that approach. However, I would suggest either replacing the existing ListZones, or merging this PR and adding the new semantics afterwards. The current implementation is not reliable.

**Comment by njuettner** [comment]
@terinjokes is there any progress on this PR? I really like to see it gets merged. I agree you proposal is better than the change in this PR but I would also like to have solution which works right now than no change at all.

**Comment by J-Ha** [comment]
Could we get some updates on this?
We have trouble with this issue since April and need this feature. 
Or we have to settle over to an another provider.

**Comment by rvalitov** [comment]
6 months have passed and still it's not merged and no updates. That's more than enough to make a decision. This repository is no longer supported by CloudFlare?

**Comment by rvalitov** [comment]
Thanks for the update!

**Comment by patryk** [comment]
Since we've decided to go alternative route, I'm closing this PR, but feel free to ping me if it's not the case. Thanks all for insights.

**Pull request closed without merging**
