### PR TITLE
Add DNS analytics support, unify dashboard and colo analytics, ip_class support & search_engine fix in dashboard analytics

### LINKED ISSUE #132: Implement DNS analytics
https://api.cloudflare.com/#dns-analytics-properties

### PR DESCRIPTION
**Pull request by robbiet480**
Fixes #132, #167

### CODE REVIEW

**Comment by elithrar** [comment]
Thanks for this! Would you mind adding tests for this too?

**Comment by robbiet480** [comment]
I plan to shortly @elithrar, just writing tests for the implementing library first (a Cloudflare exporter for Prometheus)

**Comment by elithrar** [comment]
Noted. Let me know when ready for review.

**Comment by robbiet480** [comment]
@elithrar Working on tests now. Just two quite notes:

1. Can you provide any feedback on #167 before I write tests for that. For the moment I just added a second property named `SearchEngine` alongside the existing `SearchEngines` property, but if the Cloudflare API is going to be returning `search_engine` in the future always then we should just change the JSON tag of `SearchEngines`.

2. I'm using `float64` for `ZoneDNSAnalyticsRow.Metrics`. Depending on what metrics are selected, this can actually be a float in the JSON or an integer in the JSON that Go automatically casts to a `float64`. Do you think this is correct behavior?

**Comment by robbiet480** [comment]
@elithrar Also just noticed that example DNS analytics in docs are wrong. Data is now an array, dimensions and metrics are string or float64 arrays, etc. You'll see all the differences pretty quick once you visually compare the two side by side. My tests will be against anonymized outputs of my test domain instead of the docs example.

**Comment by robbiet480** [comment]
Just threw another commit in which removes the `ZoneAnalyticsColocation` struct and has the `ZoneAnalyticsColocation` output a `ZoneAnalyticsData` struct, since `ZoneAnalyticsData` and `ZoneAnalyticsColocation` are so similar. This change makes it easier to switch out the functions depending on a users plan.

**Comment by robbiet480** [comment]
I know I said this was done yesterday, but I keep finding things to do as I continue implementing [`cloudflare_exporter`](https://github.com/robbiet480/cloudflare_exporter).

The latest commit adds support for getting [DNS Analytics By Time](https://api.cloudflare.com/#dns-analytics-by-time). Test has been written for the new functionality.

**Comment by robbiet480** [comment]
Bump.

Just added an updated `ZoneRatePlan` struct with fields not previously implemented.

**Comment by robbiet480** [comment]
@elithrar Mind merging this now? Thanks!

**Comment by jacobbednarz** [comment]
@elithrar has left Cloudflare so he probably won't be re-reviewing this 
one. @patryk has been doing some work on this library recently so I'd be 
suspecting he'll drop into this for some review.

**Comment by robbiet480** [comment]
Thanks @jacobbednarz, sorry for the ping @elithrar! Hope to hear from you soon @patryk, and thanks for picking up work on this library again :)

**Comment by elithrar** [comment]
Hey @robbiet480 - I no longer work at Cloudflare. @terinjokes or @patryk may be able to triage.

**Pull request closed without merging**
