### PR TITLE
Convert /zones -> /accounts routes for access resources

### PR DESCRIPTION
**Pull request by Justin-Holmes**
## Description

The access team has deprecated the `/zones` routes in favor of `/accounts`. The public docs should be released over the next several days that reflect the changes in this PR. I'll be referencing a corresponding PR in the Terraform provider repository once that's complete.

## Types of changes

What sort of change does your code introduce/modify?

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the code style of this project.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by Justin-Holmes** [comment]
The deprecations page will be getting an update as well, but not exactly sure on when (definitely in the near future though). There won't be an "end of life" date since we don't have any plans of removing the `/zones` routes (AFAIK).

**Comment by Justin-Holmes** [comment]
Do we have an ETA on when we think this will be released? I'm going to track this internally to make sure I don't let this fall through the cracks. 

Thanks a lot for the help!

**Comment by jacobbednarz** [comment]
It's generally a fortnightly/monthly release cycle depending on the importance of what is in it. @patryk can cut a release for this and we can start using it upstream too.

**Comment by patryk** [comment]
Thanks!

**Pull request merged**
