### PR TITLE
Basic support for account load balancers

### PR DESCRIPTION
**Pull request by tpolich**
## Description

Basic support for account level load balancers.

## Has your change been tested?

Duplicated the existing zone tests and altered them for account based LB which are identical except they don't have a "name".

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [soon] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Review by jacobbednarz — CHANGES_REQUESTED** [review]
as the CRUD method signatures already include the `*ResourceContainer` we can add a condition inside of those methods for the account level load balancers instead of using seperate new methods (we already have zone + user).

**Comment by tpolich** [comment]
the changelog check blows up on a go version mismatch but I've updated the functions to switch on the resource container level

**Comment by jacobbednarz** [comment]
updated the usage of the `ResourceContainer` to trim down one extra switch statement. let me know when this is ready with docs and we'll get it merged in.

i'll take a look at the changelog test failure but it looks correct for the usage here.

**Comment by tpolich** [comment]
oh that's a very nice improvement I didn't realize the constants actually were the text strings at the end of the day.

**Pull request merged**
