### PR TITLE
Add image upload by url

### PR DESCRIPTION
**Pull request by LewisYearsley**
## Description

The Cloudflare image API provides the ability to upload an image via a url, rather than as bytes. e.g. you might want to copy the image from some bucket to Cloudflare without having to manage the data yourself. This PR adds that functionality, heavily based on the existing file upload methodology.

## Has your change been tested?

Added test in the same fashion as the file based upload method.

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
thanks for the PR here, appreciate it! for me though, i would rather see `UploadImage` with the ability to upload all images regardless of the method used. to get this over the line, let's update the methods here to conditionally build the payload (even if you need to use multiple internal methods) instead of the multiple methods which i believe is a better experience for anyone attempting to use this.

**Comment by LewisYearsley** [comment]
No problem and for sure - I was actually in two minds about whether to have a combined signature! I’ll rework it today - thanks for looking.

**Comment by dojolew** [comment]
@jacobbednarz handled your feedback - mind taking another look when you get time? 🙏

**Comment by jacobbednarz** [comment]
thanks for this one! appreciate it 🙇

**Comment by LewisYearsley** [comment]
Thanks @jacobbednarz! Any idea when this might be released?

**Comment by jacobbednarz** [comment]
you can view the policy at https://github.com/cloudflare/cloudflare-go/blob/master/docs/changelog-process.md

**Pull request merged**
