### PR TITLE
Add support for listing R2 buckets

### PR DESCRIPTION
**Pull request by rgcostea**
## Description

Added the ability to list R2 buckets.  A recent change (#1028) added support for creating and deleting R2 buckets but was missing the ability to list R2 buckets.  This change adds support for listing R2 buckets.

## Has your change been tested?

Enhanced r2_bucket_test.go with an additional test (TestR2_ListBuckets) to list R2 buckets.  Also verified this against an active cloudflare account.

## Types of changes

What sort of change does your code introduce/modify?

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

## Notes

I could not find the repo for the api definition at api.cloudflare.com in order to update the documentation myself.  I'm happy to do that if someone can give me a pointer to it.  Also, how does this API path become a publicly documented and stable API?  Thanks.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
> I could not find the repo for the api definition at api.cloudflare.com in order to update the documentation myself.

> Also, how does this API path become a publicly documented and stable API?

once the API is stable, the service team document it and it ends up on api.cloudflare.com

**Comment by sodabrew** [comment]
@jacobbednarz harping on this again. The API endpoints are "documented" right here in code: https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/r2.ts#L14-L24

Why are there ongoing delays between making an API endpoint **public in code** and making the **documentation** public? The blog proudly exclaims that you're going to stop doing that: https://blog.cloudflare.com/content-as-a-product/

> Aligning content to the product development process means that when a new product is shipping, we have [developer documentation](https://developers.cloudflare.com/) ready to publish.

**Comment by jacobbednarz** [comment]
@sodabrew this is your first and only warning that your comment is disrespectful and unacceptable. I highly recommend reviewing the project's code of conduct as violations can result in temporary or permanent exclusion from the project. 

The wrangler2 codebase (and other tools released by the service teams) is not public documentation and is not suitable for determining an API contract for the SDKs. The team is usually controlling both sides (tool and API) so they can make sweeping changes without breaking integrations; that cannot be the same for the SDKs since we have customers relying on certain behaviours.

**Comment by sodabrew** [comment]
I'm sorry, thank you, getting on the wrong side certainly does me no good towards sharing a goal of using a great product.

> The wrangler2 codebase (and other tools released by the service teams) is not public documentation and is not suitable for determining an API contract for the SDKs. The team is usually controlling both sides (tool and API) so they can make sweeping changes without breaking integrations; that cannot be the same for the SDKs since we have customers relying on certain behaviours.

This is succinctly describing the situation. I appreciate being on the same page. I want to share that this is exactly my concern as a customer: if I build deployment tooling around wrangler2 and it changes suddenly with a coordinated release and API change, deployment workflows can be broken until an update is performed.

**Comment by jacobbednarz** [comment]
i'm in the process of adding a document outlining the endpoint support policy since it's a fairly common question (both internally and externally). hopefully that will clarify things a bit for reference.

**Comment by jacobbednarz** [comment]
the public API requirement documentation has been added to https://github.com/cloudflare/cloudflare-go/blob/master/docs/public-api-documentation.md

**Pull request closed without merging**
