### PR TITLE
[breaking] New() returns error; supports Options.

### PR DESCRIPTION
**Pull request by elithrar**
Ref: https://github.com/jamesog/cloudflare-go/issues/8

- New now has a variadic opts argument that accepts a slice of Option.
- Options for changing the underlying http.Client and http.Header map added.
- Updated flarectl to handle the updated New() signature.
- A new Error interface for returning different errors, and wrapping the
  cause, to provide easier inspection of errors without having to type-assert
  for all possible causes.

The `Error` interface will be expanded to have a `NetworkError` implementation as well for wrapping HTTP errors, and possibly a (breaking) change to handle parsing/API response errors.

We also now vendor deps for `flarectl`.

### CODE REVIEW

**Comment by elithrar** [comment]
Also: I'm happy to wait on merging this so I can add to the `Error` interface and the other work in #8 so that we break everything "once" only (for now).

**Comment by jamesog** [comment]
This is fantastic! I'd started working on golint errors and attempting tests too but you've slightly beat me to it :-)

Slightly concerned about the Travis failure from the newly-vendored items. Should we worry about that?

Re: waiting: Sure. If you've got something in progress then I'm happy to do this once.

**Comment by elithrar** [comment]
I just saw the TravisCI failures:

```
cmd/flarectl/vendor/gopkg.in/yaml.v2/decode.go:123: unreachable code
cmd/flarectl/vendor/gopkg.in/yaml.v2/emitterc.go:669: unreachable code
cmd/flarectl/vendor/gopkg.in/yaml.v2/parserc.go:169: unreachable code
The command "go tool vet ." exited with 1.
```

go vet is trying to vet the vendored dirs. I'll push a fix to `.travis.yml` that excludes these:

```sh
~/.go/src/github.com/jamesog/cloudflare-go(msilverlock/breaking-options ✔) go vet ./...
cmd/flarectl/vendor/gopkg.in/yaml.v2/decode.go:123: unreachable code
cmd/flarectl/vendor/gopkg.in/yaml.v2/emitterc.go:669: unreachable code
cmd/flarectl/vendor/gopkg.in/yaml.v2/parserc.go:169: unreachable code
exit status 1
~/.go/src/github.com/jamesog/cloudflare-go(msilverlock/breaking-options ✔) go vet $(go list ./... | grep -v '/vendor/')
```

**Comment by elithrar** [comment]
`golint` has been appeased.

I just need to finish the implementation (and usage) of the below—hopefully by the end of the week:

> The Error interface will be expanded to have a NetworkError implementation as well for wrapping HTTP errors, and possibly a (breaking) change to handle parsing/API response errors.

**Comment by oholiab** [comment]
I was just getting round to looking at this again today! Nice one!

**Comment by elithrar** [comment]
Update: I need to:

* Add `type UserError struct` that returns useful error messages about misuse (wrong credentials, usually)
* Add `type NetworkError struct` for HTTP errors
*Add `type ParseError struct` for JSON parsing errors (i.e. API changes, which should be extremely rare)
* Wrap the existing errors with these & provide some `errXXXX` strings for friendlier error strings. Callers who want the root cause can call `err.(*cloudflare.Error).Cause()` as needed.

**Comment by elithrar** [comment]
Rebased against master and resolved conflicts prior to some additional work.

**Comment by elithrar** [comment]
Pushed an update:

* Holding off on expanding concrete implementations of the `Error` interface for now until I can iterate on the design
* `cloudflare.New` returns an `error` now and uses functional options.
* Updated vendored deps in cmd/flarectl to address #55

**Comment by elithrar** [comment]
(Should be good to review & merge once CI passes)

**Comment by jamesog** [comment]
LGTM 👍

**Comment by terinjokes** [comment]
@elithrar this one now has merge conflicts :(

**Comment by elithrar** [comment]
@terinjokes Rebased, fixed conflicts, letting CI run.

**Comment by elithrar** [comment]
Rebased, fixed a nil map assignment in `New()` that was only triggered in tests.

**Pull request merged**
