### PR TITLE
feat(workers): Adds support for Workers secrets

### PR DESCRIPTION
**Pull request by pims**
## Description

TODO
Closes https://github.com/cloudflare/cloudflare-go/issues/474

## Has your change been tested?

```
go test
PASS
ok  	github.com/cloudflare/cloudflare-go	0.218s
```
## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Support for worker plain keys and secrets was added in #465 last week. Are there any differences in this PR not in that one?

**Comment by pims** [comment]
@jacobbednarz this PR does not require uploading a Worker script to set a secret.
It is more or less similar to using wrangler: https://developers.cloudflare.com/workers/tooling/wrangler/secrets/

It uses the `WorkerBindingType` created in #465.

**Comment by jacobbednarz** [comment]
🙌 thanks for the explanation

**Comment by pims** [comment]
@jacobbednarz let me know if this is a PR you'd consider merging.
I'll take a stab at updating the api documentation if this PR moves forward.

**Comment by jacobbednarz** [comment]
The only real prerequisites I have for changes are:

- That the endpoints used are publicly documented; and
- Functionality has tests

Other than that, I’m happy to review the PR.

**Comment by pims** [comment]
> That the endpoints used are publicly documented

They're used by Wrangler but I can't find the relevant documentation on [api.cloudflare.com](https://api.cloudflare.com), so I guess these are non-public endpoints. 😞

**Comment by jacobbednarz** [comment]
I couldn’t find them on developers.cloudflare.com either but if we can get the documentation added, I’m a 👍 to the PR.

**Comment by pims** [comment]
@jacobbednarz any pointers on how to update the documentation? I couldn't find a repo for the api-schema, just the repo for [developers.cloudflare.com/api/](https://github.com/cloudflare/api-docs).

**Comment by jacobbednarz** [comment]
I don’t think there is a public repository for it. If you’re internal to Cloudflare, drop @patryk a message and he can walk you through the steps to get it into a backlog. Otherwise, a support ticket to Cloudflare Support will get routed to the right place. 

I’m just an interested party/contributed outside of Cloudflare as I maintain the Terraform provider 😊

**Comment by pims** [comment]
@jacobbednarz ah! No wonder I hadn't seen your name in our internal chat 😅  I'll file a JIRA.
Thanks again for taking the time to look at this PR.

**Comment by jacobbednarz** [comment]
Don’t worry, you’re not the first to be confused😄 Happy for you to ping me when you’re ready here as this is something that would definitely be useful upstream in Terraform too.

**Comment by patryk** [comment]
Thanks!

**Pull request merged**
