### PR TITLE
Match CustomHostname.SSL.VerificationErrors struct to actual API response

### PR DESCRIPTION
**Pull request by jpreynat**
## Description

The [current API documentation for custom hostnames](https://api.cloudflare.com/#custom-hostname-for-a-zone-custom-hostname-details) in a zone states that the custom hostname `ssl.verification_errors` is an object with the type:

```ts
interface VerificationError {
  message: string;
}

interface CustomHostname {
  // ...
  ssl: {
    // ...
    verification_errors: VerificationError;
  }
}
```

However, after testing it in real conditions, the API actually returns an array of such objects:

```ts
interface CustomHostname {
  // ...
  ssl: {
    // ...
    verification_errors: VerificationError[];
  }
}
```

I encountered this error using cloudflare-go, which led to the following error:
```
error unmarshalling the JSON response: json: cannot unmarshal array into Go struct field
CustomHostnameSSL.result.ssl.validation_errors of type cloudflare.CustomHostnameSSLValidationErrors
```

This PR fixes the struct definition to properly deserialize the JSON response in this library.
I've also sent a support request to Cloudflare to ask for updating the documentation regarding this issue.

## Has your change been tested?

I've updated the existing test to match the actual response from the API.

## Types of changes

What sort of change does your code introduce/modify?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Review by nickysemenza — APPROVED** [review]
You're right, the example response of https://api.cloudflare.com/#custom-hostname-for-a-zone-create-custom-hostname
should be
```diff
ssl: {
      ...
-    "validation_errors": {
+    "validation_errors": [{
        "message": "SERVFAIL looking up CAA for app.example.com"
-     },
+     }],
}
```

nit: in your description/title you mention _verification_ issues, but your change correctly fixes _validation_ errors.

**Comment by jpreynat** [comment]
Oh yes, sorry for the mistake on this.
I meant validation indeed 👍

**Comment by jacobbednarz** [comment]
Looks like we are still pending a response from Cloudflare on this via #527

**Review by patryk — APPROVED** [review]

**Comment by patryk** [comment]
Thanks everyone!

**Pull request merged**
