### PR TITLE
Add txt_name & txt_value fields (DNS validation) to CustomHostname struct

### PR DESCRIPTION
**Pull request by cdloh**
## Description

Adds txt_name and txt_value fields to CustomHostname struct that are needed for SSL Verification when using the txt method

## Has your change been tested?

No unit tests yet. Unsure if needed.

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
unit tests please. you should be able to update existing HTTP mock responses and assert the struct values match.

**Comment by cdloh** [comment]
Added!

**Comment by cdloh** [comment]
Note I've added it as a seperate test as all the other tests used HTTP validation.

**Comment by jacobbednarz** [comment]
thanking you! 👏

**Pull request merged**
