### PR TITLE
Add Codecov.io

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
Please review. Thanks

**Comment by jamesog** [comment]
There's conflicts because of your other change to the Travis config.

@elithrar do you know what our policy is on adding services like this? I assume it's OK but not sure...

**Comment by elithrar** [comment]
I'd prefer not to wire up a third party service at this stage without additional review. Our TravisCI build could instead be amended to output coverage on test runs - e.g. 

```diff
-   - go test -v -race $(go list ./... | grep -v '/vendor/')
+   - go test -v -cover -race $(go list ./... | grep -v '/vendor/')
```

**Comment by gliptak** [comment]
What codecov does is reading the coverage.txt file generated by Travis and displays it as history/charts ...

**Comment by elithrar** [comment]
Sure, but it needs read/write access to the repo to do it. That's the
problem.

**Comment by gliptak** [comment]
https://github.com/codecov/codecov-bash/issues/52

**Comment by gliptak** [comment]
@elithrar Would running upload using ```curl``` be acceptable? Thanks

**Comment by elithrar** [comment]
That looks better. Two questions:

- what is the token in the URL?
- who owns the account?

**Comment by gliptak** [comment]
I do not believe ```token``` is required for public repositories.
As for the account ownership question, my understanding is that Github userids with write access to the repository will have configuration access to https://codecov.io/gh/cloudflare/cloudflare-go

**Pull request closed without merging**
