### PR TITLE
Add session_affinity_attributes field to LoadBalancer

### PR DESCRIPTION
**Pull request by tingwai**
## Description

`session_affinity_attributes` is a new field to set the samesite and
secure attributes in a load balancer session affinity cookie. Also fixed
broken links in load balancer API reference.

## Has your change been tested?

Add new fields to load balancing tests which verify the input struct matches the returning JSON/struct.

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Are you able to point to the documentation for this new field? I can't seem to find it on either the API or developer documentation.

**Comment by tingwai** [comment]
@jacobbednarz In the create load balance API docs under `Optional parameters` section, there should be a `session_affinity_attributes` object with fields `samesite` and `secure`, https://api.cloudflare.com/#load-balancers-create-load-balancer. These fields should similarly exist for [update load balancer](https://api.cloudflare.com/#load-balancers-update-load-balancer) and [patch load balancer](https://api.cloudflare.com/#load-balancers-patch-load-balancer).

**Comment by jacobbednarz** [comment]
Thanks @tingwai 🙇 Not sure if this is a new thing but I don't think it was there when I initially checked (either that or PEBKAC 😛 )

**Comment by patryk** [comment]
Thanks @tingwai!

**Pull request merged**
