### PR TITLE
add delete for url normalization

### PR DESCRIPTION
**Pull request by jafowler**
## Description
Adds delete function for url normalization that will disable the feature. 

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by jacobbednarz** [comment]
do we have the public API docs for this yet? we already have #1078 but that takes a different approach which leads me to want to wait the docs for this to confirm stability.

**Comment by jafowler** [comment]
> do we have the public API docs for this yet? we already have #1078 but that takes a different approach which leads me to want to wait the docs for this to confirm stability.

no public docs yet, let me follow up with the team.

**Comment by jacobbednarz** [comment]
is this still required?

**Comment by jacobbednarz** [comment]
closing this off due to being stale. if we still need this, let's open a new PR and port the changes there to get this over the line.

**Comment by jameskillough627** [comment]
hi

**Pull request closed without merging**
