### PR TITLE
Add support for account load balancers pools and monitors

### PR DESCRIPTION
**Pull request by Cyb3r-Jak3**
## Description

Adds support for Account Load Balancer [Monitors ](https://api.cloudflare.com/#account-load-balancer-monitors-list-monitors) and [Pools](https://api.cloudflare.com/#account-load-balancer-pools-properties).
Needed for https://github.com/cloudflare/terraform-provider-cloudflare/issues/1876

## Has your change been tested?
Updated unit tests and they pass

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

### CODE REVIEW

**Comment by Cyb3r-Jak3** [comment]
It looks like this is only for account load balancers, which don't seem to be in repo currently. I'll change this PR into adding account load balancers, monitors, and pools.
https://api.cloudflare.com/#account-load-balancer-monitors-properties

**Comment by jacobbednarz** [comment]
LBs are a little confusing but pools and monitors are account only level resources where the LBs themselves are zone level. 

There are some older (semi-deprecated) user level resources but we can ignore them here.

**Comment by Cyb3r-Jak3** [comment]
From I have seen, the only LB monitors and pools referenced here are the user level resources.

[User Load Balancer Monitors](https://api.cloudflare.com/#load-balancer-monitors-list-monitors) | [Search](https://github.com/cloudflare/cloudflare-go/search?q=https%3A%2F%2Fapi.cloudflare.com%2F%23load-balancer-monitors-list-monitors)

[User Load Balancer Pools](https://api.cloudflare.com/#load-balancer-pools-properties) | [Search](https://github.com/cloudflare/cloudflare-go/search?q=https%3A%2F%2Fapi.cloudflare.com%2F%23load-balancer-pools-list-pools)

I do not see API references links for:

[Account Load Balancer Monitors](https://api.cloudflare.com/#account-load-balancer-monitors-list-monitors) | [Search](https://github.com/cloudflare/cloudflare-go/search?q=https%3A%2F%2Fapi.cloudflare.com%2F%23account-load-balancer-pools-list-pools)

[Account Load Balancer Pools](https://api.cloudflare.com/#account-load-balancer-pools-list-pools) | [Search](https://github.com/cloudflare/cloudflare-go/search?q=https%3A%2F%2Fapi.cloudflare.com%2F%23account-load-balancer-monitors-list-monitors)

[Account Load Balancer Search](https://api.cloudflare.com/#account-load-balancer-search-properties) | [Search](https://github.com/cloudflare/cloudflare-go/search?q=https%3A%2F%2Fapi.cloudflare.com%2F%23account-load-balancer-search-search-resources)

**Comment by jacobbednarz** [comment]
if i understand the intent here, this isn't the approach we want. the [experimental client docs](https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.md) aim to allow us to use a single method irrespective of the resource assignment (user, zone, account).

to move this forward, check out #931 and use it as the starting point (feel free to take the commits and start a new PR) with @gofish's feedback which was basically:

- pools + monitors are account only
- lb's are zone only (but we can also accept user) levels ones too.

**Comment by jacobbednarz** [comment]
let me get a PR up for you as a starting point to clarify the points as they are quite confusing.

**Comment by jacobbednarz** [comment]
updated in #1084

**Pull request closed without merging**
