### PR TITLE
Teams untrusted cert action

### PR DESCRIPTION
**Pull request by alyssamw**
## Description

Add new teams rule setting field, "untrusted_cert". This is an object containing an "action" field which can have 3 values: pass_through, block, or error.

Ignore commit 7e6a0e7053a69595ee2fdc12838aa3c7ee4227fe which is being used for terraform-provider PR -- will delete before merging

## Has your change been tested?

Updated the serialization tests, nothing else to test here.

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [  x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ ] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by alyssamw** [comment]
API docs are pending internal release

**Comment by jacobbednarz** [comment]
thanks! this all looks good. i'll circle back once we have the API docs sorted 😃

**Comment by alyssamw** [comment]
Hi Jacob, the docs got released on https://developers.cloudflare.com/api/operations/zero-trust-gateway-rules-create-zero-trust-gateway-rule, could I get this PR merged?

Edit: new commit fixes merge conflicts, lint errors

**Comment by jacobbednarz** [comment]
thanks @alyssamw 🏆

**Pull request merged**
