### PR TITLE
add list waf rule groups

### PR DESCRIPTION
**Pull request by sbfaulkner**
This PR adds an entrypoint to list WAF rule groups as per https://api.cloudflare.com/#waf-rule-groups-list-rule-groups

It will contribute to implementation of #321

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sbfaulkner** [comment]
@patryk @jacobbednarz would appreciate you taking a look ... I'm creating a few PRs to update the terraform provider

**Comment by sbfaulkner** [comment]
what's the merge and/or release cycle for this pkg?
thanks

**Comment by jacobbednarz** [comment]
The change is merged following review and everyone happy with it (generally a couple of folks). A new release is cut whenever the functionality is usable in a downstream system or warrants one. Short version, as needed 🙂

**Comment by sbfaulkner** [comment]
@patryk this one too?

**Comment by patryk** [comment]
Looks good, just need to fix the merge conflict.

**Comment by patryk** [comment]
Could you rebase on top of current master?

**Comment by sbfaulkner** [comment]
@sbfaulkner should be good now

**Comment by patryk** [comment]
Splendid! Merged. Let me know if you need release cut, so we can upstream for Terraform.

**Pull request merged**
